version: '3.1'

services:

  wordpress:
    image: wordpress:php7.2
    ports:
      - "${DOCKER_WORDPRESS_PORT}:80"
    depends_on:
      - mysql
    volumes:
      - ./.data/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"

  mysql:
    image: mysql:5.7
    expose:
      - 3306
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD}"
    volumes:
      - ./.data/mysql:/var/lib/mysql
    restart: always

  portainer:
    image: portainer/portainer
    ports:
      - "${DOCKER_PORTAINER_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data portainer/portainer
      - ./.data/portainer:/data
