version: '3.1'

services:

  wordpress:
    image: wordpress:php7.2
    ports:
      - 8080:80
    depends_on:
      - mysql
    volumes:
      - ./.data/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  mysql:
    image: mysql:5.7
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./.data/mysql:/var/lib/mysql
    restart: always
